/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GerarRouteImport } from './routes/gerar'
import { Route as PrintRouteImport } from './routes/print'
import { Route as PropostasRouteImport } from './routes/propostas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GerarRoute = GerarRouteImport.update({
  id: '/gerar',
  path: '/gerar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gerar': typeof GerarRoute
  '/print': typeof PrintRoute
  '/propostas': typeof PropostasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gerar': typeof GerarRoute
  '/print': typeof PrintRoute
  '/propostas': typeof PropostasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gerar': typeof GerarRoute
  '/print': typeof PrintRoute
  '/propostas': typeof PropostasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gerar' | '/print' | '/propostas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gerar' | '/print' | '/propostas'
  id: '__root__' | '/' | '/gerar' | '/print' | '/propostas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GerarRoute: typeof GerarRoute
  PrintRoute: typeof PrintRoute
  PropostasRoute: typeof PropostasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerar': {
      id: '/gerar'
      path: '/gerar'
      fullPath: '/gerar'
      preLoaderRoute: typeof GerarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GerarRoute: GerarRoute,
  PrintRoute: PrintRoute,
  PropostasRoute: PropostasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
